### ISSUE TITLE
pretrained model feature

### ISSUE THREAD

**Issue by gongshichina** [LuyaooChen/uninformed-students-pytorch#1]
Hello, thanks for your codes! Can I ask why you fetch the first 512-d vector from the fc's output? I guess we should extract from the fc's input, that is, a 512-d feature.

**Comment by LuyaooChen** [comment]
我当时没有多做考虑，可能对论文理解有偏差。我不知道这会对结果产生什么影响，但我认为你的做法更合理。我会修改过来。谢谢你提出问题。
