### ISSUE TITLE
feature map extracted from student and teacher

### ISSUE THREAD

**Issue by Fantasy1120** [LuyaooChen/uninformed-students-pytorch#2]
Hello, thanks for your work! Can I ask if there is any difference between the feature map extracted from student and teacher? When I visualize the feature maps, they seem to be same.

**Comment by LuyaooChen** [comment]
I think the student and teacher feature maps extracted from good images should be same, bud different from anomaly images.

**Comment by Fantasy1120** [comment]
> I think the student and teacher feature maps extracted from good images should be same, bud different from anomaly images.

I think so…But from the visual results, whether it is normal or abnormal examples, they are same. It's so strange…
They are original image, teacher's feature map, student's feature map, anomaly map, respectively.

![image](https://user-images.githubusercontent.com/61446184/98541682-c6dc5a00-22ca-11eb-9f30-f7802e5fcf69.png)

**Comment by LuyaooChen** [comment]
How did you visualize these?  Teacher and students output 128-d vector.

**Comment by Fantasy1120** [comment]
> How did you visualize these? Teacher and students output 128-d vector.

Just calculate the mean on the channel dimension. I tried to observe the 128-d value of these two feature maps at (150,220), this is results.

![image](https://user-images.githubusercontent.com/61446184/98828558-2e350e00-2473-11eb-80eb-46646ca9782b.png)

![image](https://user-images.githubusercontent.com/61446184/98828399-ff1e9c80-2472-11eb-94e1-9bf64c5c12de.png)

**Comment by Fantasy1120** [comment]
Just calculate the mean on the channel dimension. I tried to observe the 128-d value of these two feature maps at (150,220), this is results.
![image](https://user-images.githubusercontent.com/61446184/98828722-61779d00-2473-11eb-8278-9b392a4a1523.png)

![image](https://user-images.githubusercontent.com/61446184/98828913-9388ff00-2473-11eb-9748-fa699df58ff4.png)

![image](https://user-images.githubusercontent.com/61446184/98829085-c16e4380-2473-11eb-8dbf-502696765a97.png)

**Comment by LuyaooChen** [comment]
It's really strange... Here is my result of visualiztion.
There are the teacher with patch_size 33, and its 3 students. The vectors of student2 and student3 are same. Even more strange is that I tried to retrain the s2 and s3 or I swapped s1 and s2/s3,  I got the same result. s1 is always greater than s2 and s3, and s2 is equal to s3.
![patch33](https://user-images.githubusercontent.com/48198621/98929302-e6b38e00-2515-11eb-983d-20b6ce30ff26.jpg)
![patch33_2](https://user-images.githubusercontent.com/48198621/98929692-7bb68700-2516-11eb-86d2-3177ed2ea340.jpg)
![res](https://user-images.githubusercontent.com/48198621/98932012-bc63cf80-2519-11eb-837b-28a5108439e3.jpg)

And here is teacher with patch_size 17. The outputs of s2, s3 and teacher are same.
![patch17](https://user-images.githubusercontent.com/48198621/98931643-3f385a80-2519-11eb-97ec-ac65836e2c10.jpg)
But when I use s2 and s3 only, s2 is not equal to s3 and t. 
![patch17_2](https://user-images.githubusercontent.com/48198621/98932562-752a0e80-251a-11eb-91f4-bcb7e34d6a66.jpg)

I am sorry that I can't explain this. It seem to there is a bug in evaluate.py or visualiztion...

**Comment by LuyaooChen** [comment]
@Fantasy1120 You can try to plot (t_pixel-s_pixel). I found it is not equal to zero, just small.    But I have comfirmed that when I use multiple students, actually the students are totally same, just one student can work. I am trying to fix this bug.

**Comment by Fantasy1120** [comment]
> u can try to plot (t_pixel-s_pixel). I found it is not equal to zero, just small. But I have comfirmed that when I use multiple students, actually the students are totally same, just one student can work. I am trying to fix this bug.

Okkk,Thanks for your reply! I’ll try debugging as well.

**Comment by LuyaooChen** [comment]
@Fantasy1120 !! I have updated evaluate.py.  Just add a line at Line 117!  I made a stupid mistake.   Because I used the same _teacher to create teacher and students before, they have the same address actually.

**Comment by Fantasy1120** [comment]
> @Fantasy1120 !! I have updated evaluate.py. Just add a line at Line 117! I made a stupid mistake. Because I used the same _teacher to create teacher and students before, they have the same address actually.

It works~Thank you soooo much
